### ISSUE TITLE
Can't install this on my laptop

### ISSUE THREAD

**Issue by ShizukaKitakami55** [Boorunaut/Boorunaut#187]
Downloaded latest python 3 version (3.13.1) and git version (2.47.1)

When I try however... I get this instead.

```
py -m pip install "git+https://github.com/Boorunaut/Boorunaut.git" --pre
Collecting git+https://github.com/Boorunaut/Boorunaut.git
  Cloning https://github.com/Boorunaut/Boorunaut.git to c:\users\shizu\appdata\local\temp\pip-req-build-75mxiu04
  Running command git clone --filter=blob:none --quiet https://github.com/Boorunaut/Boorunaut.git 'C:\Users\shizu\AppData\Local\Temp\pip-req-build-75mxiu04'
  Resolved https://github.com/Boorunaut/Boorunaut.git to commit d244bbd66c7182c77ba2180877390d542ce49cc4
  Preparing metadata (setup.py) ... done
Collecting diff-match-patch==20200713 (from Boorunaut==0.5.0)
  Using cached diff_match_patch-20200713-py3-none-any.whl.metadata (5.3 kB)
Collecting Django==5.0.4 (from Boorunaut==0.5.0)
  Using cached Django-5.0.4-py3-none-any.whl.metadata (4.1 kB)
Collecting django-crispy-forms==1.14.0 (from Boorunaut==0.5.0)
  Using cached django_crispy_forms-1.14.0-py3-none-any.whl.metadata (4.8 kB)
Collecting django-markdownify==0.9.2 (from Boorunaut==0.5.0)
  Using cached django_markdownify-0.9.2-py3-none-any.whl.metadata (2.4 kB)
Collecting django-role-permissions==3.1.1 (from Boorunaut==0.5.0)
  Using cached django-role-permissions-3.1.1.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Collecting django-simple-history==3.2.0 (from Boorunaut==0.5.0)
  Using cached django_simple_history-3.2.0-py3-none-any.whl.metadata (18 kB)
Collecting django-taggit==5.0.1 (from Boorunaut==0.5.0)
  Using cached django_taggit-5.0.1-py3-none-any.whl.metadata (3.4 kB)
Collecting ffmpeg-python==0.2.0 (from Boorunaut==0.5.0)
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Collecting markdown2==2.4.7 (from Boorunaut==0.5.0)
  Using cached markdown2-2.4.7-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting olefile==0.46 (from Boorunaut==0.5.0)
  Using cached olefile-0.46.zip (112 kB)
  Preparing metadata (setup.py) ... done
Collecting Pillow==10.3.0 (from Boorunaut==0.5.0)
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\shizu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\shizu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shizu\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\shizu\AppData\Local\Temp\pip-build-env-07hisqrr\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shizu\AppData\Local\Temp\pip-build-env-07hisqrr\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\shizu\AppData\Local\Temp\pip-build-env-07hisqrr\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Tried the same input (without pre) yet it still won't install.

Thanks for your help.

**Comment by LucasCTN** [comment]
Could you try `pip install Pillow==10.3.0` by itself first? Does it throw any error by it's own?
